In [ ]:
%load_ext rpy2.ipython

In [ ]:
%%R
# Operador de asignación <-
nacionalidad <- "Mexicana"
estatura <- 1.53
# estudiantes_sesion1 <- 27
estudiantes_sesion1 <- as.integer(7)
# estudiantes_sesion1 <- 27L
usa_lentes <- TRUE

# Estructuras de datos

Las estructuras de datos son objetos que contienen datos, lo que las distingue es su *número de dimensiones* y si son *homogeneas* o *heterogeneas*.

Las estructuras homogeneas son:
1. Vector
2. Matriz
3. Array

Las estructuras heterogeneas son:
1. Lista
2. Dataframe


In [ ]:
%%R
print(is.vector(estudiantes_sesion1))
print(length(estudiantes_sesion1))

print(is.vector(nacionalidad))
print(length(nacionalidad))


[1] TRUE
[1] 1
[1] TRUE
[1] 1


## Creación de vectores

Se usa la función **c()**

In [ ]:
%%R
vec_edades <- c(32, 29, 48, 40, 24)
print(vec_edades)
print(length(vec_edades))

vec_nacionalidades <- c("Mexicana", "Guatemalteca", "Venezolana")
print(vec_nacionalidades)
print(length(vec_nacionalidades))
print(class(vec_nacionalidades))

[1] 32 29 48 40 24
[1] 5
[1] "Mexicana"     "Guatemalteca" "Venezolana"  
[1] 3
[1] "character"


In [ ]:
%%R
vec_nacionalidades <- c(vec_nacionalidades, "Dominicana")
vec_nacionalidades

[1] "Mexicana"     "Guatemalteca" "Venezolana"   "Dominicana"  


In [ ]:
%%R
vec_mix <- c(nacionalidad, estatura, usa_lentes, estudiantes_sesion1)
print(class(vec_mix))
print(vec_mix)

[1] "character"
[1] "Mexicana" "1.53"     "TRUE"     "7"       


## Secuencias

Para generar una secuencia se emplea el operador **:**

In [ ]:
%%R
print(-10:10)
print(20:10)
print(2.5:15.5)
# Se redondean las cifras del segundo valor
print(2:15.5)

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8
[20]   9  10
 [1] 20 19 18 17 16 15 14 13 12 11 10
 [1]  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5 15.5
 [1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15


Generación de un vector mediante una secuencia

In [ ]:
%%R
vec_num <- c(1:10)
vec_num

 [1]  1  2  3  4  5  6  7  8  9 10


## Operaciones aritmeticas con vectores

In [ ]:
%%R
vec_num_neg = vec_num * -1
vec_num_coc = vec_num %/% 2
vec_num_add = vec_num + 10
vec_num_less = vec_num <= 5
print(vec_num_neg)
print(vec_num_coc)
print(vec_num_add)
print(vec_num_less)

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10
 [1] 0 1 1 2 2 3 3 4 4 5
 [1] 11 12 13 14 15 16 17 18 19 20
 [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE


# Matrices y arrays

Estas estructuras de datos son vectores multidimensionales. En el caso de las matrices tienen **dos dimensiones**, largo y alto, mientras que un array tiene un número arbitrario de dimensiones.

## Matrices

### Creación

Se emplea la función **matrix()**, la cual acepta 2 argumentos *nrow* y *ncol*

In [ ]:
%%R

# Los datos se acomodan de arriba hacia abajo y de izquierda a derecha, hasta completar el número de filas y columnas
print(matrix(1:10))
# Cinco renglones
print(matrix(1:10, nrow=5))
# Tres columnas. Los elementos se reciclan
print(matrix(1:10, ncol=3))
# Tres renglones y tres columnas. Se omiten los valores que ya no se pueden acomodar
print(matrix(1:10, nrow=3, ncol=3))

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10
     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7    1
[4,]    4    8    2
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In addition: Warning messages:
1: In matrix(1:10, ncol = 3) :
  data length [10] is not a sub-multiple or multiple of the number of rows [4]
2: In matrix(1:10, nrow = 3, ncol = 3) :
  data length [10] is not a sub-multiple or multiple of the number of rows [3]


### Unión de vectores para crear una matriz

Se usan las funciones
* *cbind()* Une los vectores como columnas
* *rbind()* Une los vectores como filas

In [ ]:
%%R
mat_cols = cbind(vec_num_add, vec_num_coc, vec_num_less, vec_num_neg)
mat_rows = rbind(vec_num_less, vec_num_add, vec_num_neg, vec_num_coc)
print(mat_cols)
print(mat_rows)

      vec_num_add vec_num_coc vec_num_less vec_num_neg
 [1,]          11           0            1          -1
 [2,]          12           1            1          -2
 [3,]          13           1            1          -3
 [4,]          14           2            1          -4
 [5,]          15           2            1          -5
 [6,]          16           3            0          -6
 [7,]          17           3            0          -7
 [8,]          18           4            0          -8
 [9,]          19           4            0          -9
[10,]          20           5            0         -10
             [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
vec_num_less    1    1    1    1    1    0    0    0    0     0
vec_num_add    11   12   13   14   15   16   17   18   19    20
vec_num_neg    -1   -2   -3   -4   -5   -6   -7   -8   -9   -10
vec_num_coc     0    1    1    2    2    3    3    4    4     5


In [ ]:
%%R
# dim es exclusivo de matrices o arrays. En caso de usarse en un objeto unidimensional da NULL
print(dim(mat_cols))
print(dim(vec_edades))

[1] 10  4
NULL


### Operaciones con matrices

In [ ]:
%%R

# Para calcular la transpuesta de una matriz se emplea la función (t)
mat_cols_t = t(mat_cols)
mat_cols_t

             [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
vec_num_add    11   12   13   14   15   16   17   18   19    20
vec_num_coc     0    1    1    2    2    3    3    4    4     5
vec_num_less    1    1    1    1    1    0    0    0    0     0
vec_num_neg    -1   -2   -3   -4   -5   -6   -7   -8   -9   -10


In [ ]:
%%R
print(mat_cols_t + mat_rows)
print(mat_cols * 2)
print(mat_rows %% 5)

             [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
vec_num_add    12   13   14   15   16   16   17   18   19    20
vec_num_coc    11   13   14   16   17   19   20   22   23    25
vec_num_less    0   -1   -2   -3   -4   -6   -7   -8   -9   -10
vec_num_neg    -1   -1   -2   -2   -3   -3   -4   -4   -5    -5
      vec_num_add vec_num_coc vec_num_less vec_num_neg
 [1,]          22           0            2          -2
 [2,]          24           2            2          -4
 [3,]          26           2            2          -6
 [4,]          28           4            2          -8
 [5,]          30           4            2         -10
 [6,]          32           6            0         -12
 [7,]          34           6            0         -14
 [8,]          36           8            0         -16
 [9,]          38           8            0         -18
[10,]          40          10            0         -20
             [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
vec_num_les

# Dataframes

Son estructuras de datos de dos dimensiones que pueden contener diferentes tipos de datos, es decir, son heterogéneas. Es la estructura más usada para el análisis de datos.

Los datos de una columna son de un mismo tipo, pues representan atributos, rasgos o variables. Por otro lado, los datos de un reglon pueden ser de diferentes tipos, ya que representan la información de un individuo u observaciones.

Se pueden realizar operaciones aritméticas sólo en sus columnas numéricas, en el resto asigna NA

NOTA: Se debe tener presente que un dataframe esta compuesto por vectores.

## Creación de dataframes

Se usa la función **data.frame()**

In [ ]:
%%R
df_estudiantes <- data.frame(
   "nacionalidd" = c("Mexicana", "Guatemalteca", "Venezolana", "Dominicana"),
   "edad" = c(32, 29, 48, 40),
   "sexo" = c("M", "F", "M", "F")
)

df_estudiantes

  nacionalidad edad sexo
1     Mexicana   32    M
2 Guatemalteca   29    F
3   Venezolana   48    M
4   Dominicana   40    F


In [ ]:
%%R
print(dim(df_estudiantes))
# Numero de columnas
print(length(df_estudiantes))
# Nombres de las columnas
print(names(df_estudiantes))
print(class(df_estudiantes))

[1] 4 3
[1] 3
[1] "nacionalidad" "edad"         "sexo"        
[1] "data.frame"


In [ ]:
%%R
# Creacion de un dataframe a partir de una matrix
# df_mat <- as.data.frame(matrix(1:15, ncol=5))
df_mat <- as.data.frame(matrix(1:15, ncol=5))
df_mat <- as.data.frame(mat_cols_t)

# Listas

Son estructuras unidimensionales (solo tienen largo) heterogéneas, es decir, cada uno de sus elementos puede ser de diferente tipo. A diferencia de las estructuras vistas, no se pueden realizar operaciones aritméticas en una lista.

Para saber el número de elementos de la lista se emplea **length**.

## Creación

Se emplea la función **list()**

In [ ]:
%%R
lst_mix <- list("dataframe" = df_estudiantes, "matriz" = mat_cols, "vector" = vec_nacionalidades)
lst_mix

$dataframe
  nacionalidad edad sexo
1     Mexicana   32    M
2 Guatemalteca   29    F
3   Venezolana   48    M
4   Dominicana   40    F

$matriz
      vec_num_add vec_num_coc vec_num_less vec_num_neg
 [1,]          11           0            1          -1
 [2,]          12           1            1          -2
 [3,]          13           1            1          -3
 [4,]          14           2            1          -4
 [5,]          15           2            1          -5
 [6,]          16           3            0          -6
 [7,]          17           3            0          -7
 [8,]          18           4            0          -8
 [9,]          19           4            0          -9
[10,]          20           5            0         -10

$vector
[1] "Mexicana"     "Guatemalteca" "Venezolana"   "Dominicana"  



In [ ]:
%%R
print(length(lst_mix))
print(class(lst_mix))

[1] 3
[1] "list"
